name: Build website

on:
  push:
    branches: [ 'master' ]
    tags: [ 'v*.*', 'v*.*.*', 'v*.*.*-*' ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.115.1'
          # extended: true

      - name: Build
        run: hugo --minify

      - uses: actions/upload-artifact@v3
        with:
          name: website
          path: public/

      # prepare release
      - name: create artifact archive
        run: tar -zcf 'public.tar.gz' public/

      ## release (when tag present)
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            public.tar.gz
          fail_on_unmatched_files: true
        if: startsWith(github.ref, 'refs/tags/')


